name: Android Debug Build

on:
  push:
    branches: [ master ]
    tags: 
     - "loyal*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    ## Project checkout ##
      - name: Project checkout
        uses: actions/checkout@v2.3.4
        with:
          path: hotmart-test
    
    ## Dependency checkout ##
      - name: Dependency checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: cassioferrazzo/external-script
          path: external-script
          
    ## Java JDK setup ##    
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
    ## Execute Dependency Scripts ##
      - name: Dependency Scripts
        run: |
         pwd
         ls -la
         cd hotmart-test
         pwd
         ls -la
         chmod +x ./prepare-env.sh
         ./prepare-env.sh
         
    ## Execute unit tests
      - name: Unit Tests
        run: |
         cd hotmart-test 
         ./gradlew testDebugUnitTest
         
    ## Test Report
      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
        with:
         path: hotmart-test/app/build/test-results
        
    ## Gradle Build ##      
      - name: Gradle Build
        run: |
         cd hotmart-test
         ./gradlew build
        
    ## Upload the APK ##
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: hotmart-test/app/build/outputs/apk/debug/app-debug.apk
