name: Android Debug Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: 
     - "loyal*"

jobs:
  build:
    runs-on: macos-latest
    steps:
    
    ## Project checkout ##
      - name: Project checkout
        uses: actions/checkout@v2.3.4
        with:
          path: hotmart-test
    
    ## Dependency checkout ##
      - name: Dependency checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: cassioferrazzo/external-script
          path: external-script
          
    ## Java JDK setup ##    
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
    ## Execute Dependency Scripts ##
      - name: Dependency Scripts
        run: |
         pwd
         ls -la
         cd hotmart-test
         pwd
         ls -la
         chmod +x ./prepare-env.sh
         ./prepare-env.sh
         
    ## Execute Unit Tests
      - name: Unit Tests
        run: |
         cd hotmart-test 
         ./gradlew testDebugUnitTest
                  
    ## Execute Instrumented Tests
      - name: Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2.19.1
        with:
          api-level: 23
          target: default
          arch: x86
          profile: Nexus 6
          working-directory: hotmart-test
          script: ./gradlew connectedCheck --stacktrace
        
    ## Gradle Build ##      
#      - name: Gradle Build
#        run: |
#         cd hotmart-test
#         ./gradlew assembleRelease
        
      - name: Gradle Build
        uses: gradle/gradle-build-action@v1.4.1
        with:
          arguments: build
          build-root-directory: ./hotmart-test/
        
    ## Upload the APK ##
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: hotmart-test/app/build/outputs/apk/debug/app-debug.apk
