name: Android Debug Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    
    ## Project checkout ##
      - name: Project checkout
        uses: actions/checkout@v2.3.4
        with:
          path: hotmart-test
    
    ## Dependency checkout ##
      - name: Dependency checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: cassioferrazzo/external-script
          path: external-script
          
    ## Java JDK setup ##    
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
    ## Execute Dependency Scripts ##
      - name: Dependency Scripts
        run: |
         pwd
         ls -la
         cd hotmart-test
         pwd
         ls -la
         chmod +x ./prepare-env.sh
         ./prepare-env.sh

    ## Gradle Build ##      
      - name: Gradle Build
        uses: gradle/gradle-build-action@v1.3.3
        with:
          arguments: build
          build-root-directory: ./hotmart-test
        
    ## Upload the APK ##
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: hotmart-test/app/build/outputs/apk/debug/app-debug.apk
