name: Android Debug Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    ## Repository checkout ##
      - name: Checkout
        uses: actions/checkout@v2.3.4
    
    ## Java JDK setup ##    
      - name: Set up JDK 11
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'zulu'
          java-version: '11'
          
    ## Gradle Build ##      
      - name: Gradle Build
        id: buildAPK
        uses: gradle/gradle-build-action@v1.3.3
        with:
          arguments: build
        
    ## Upload the APK ##
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      
